FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard/ ./dashboard/
COPY config.yaml .

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py"]
