FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY gateway/ ./gateway/
COPY config.yaml .
COPY .env .

CMD ["python", "gateway/email_listener.py"]
